### ISSUE TITLE
Issue during "make && make install"

### ISSUE THREAD

**Issue by TekPhreak-Git** [huo-ju/photoprism-freebsd-port#12]
I encountered this error while running the 'make && make install' portion of the process:

![image](https://user-images.githubusercontent.com/42393851/115099816-0c4a2680-9efe-11eb-8349-83a539a4fc03.png)

Not sure how to progress from here.

I appreciate your help.

Thank you!

**Comment by huo-ju** [comment]
`wget` not installed?

Please install the `ports/ftp/wget` and try again.

**Comment by TekPhreak-Git** [comment]
I apologize, I thought it would be installed by default. That does seem to be the cause of the issue since it is installing now. Thank you for your help! It is appreciated!

**Comment by huo-ju** [comment]
Glad to know it works, thanks for the feedback.
