### ISSUE TITLE
update to latest version

### ISSUE THREAD

**Issue by jwcasl** [huo-ju/photoprism-freebsd-port#16]
Thank you for this port. With this and the notes found in this thread (https://www.truenas.com/community/threads/how-to-install-photoprism-in-jail.88862/page-5) I was able to get photoprism to compile and work in freebsd.

However, the version in the port still sometimes rotates an HEIF photo when converting to jpeg. It looks like this was fixed in the 5/20/21 version of photoprism. Is it possible to update the port to the the 5/20/21 or latter version?

Thanks again for the great work.

**Comment by psa** [comment]
Fixed in #18

**Comment by psa** [comment]
Also, if you're running FreeBSD 13.0, you can pull a binary release from https://github.com/psa/photoprism-freebsd-port/releases

**Comment by jwcasl** [comment]
Thank you!

**Comment by dml33** [comment]
Awesome that there is now a binary package! I am also running it in a FreeBSD 12.2 jail in XigmaNAS. Last time, it took me a whole day to compile the whole port of the 20210505 version, apart from solving some compiling problems regarding Tensorflow (a missing patch and set CPU limitation to 2 cores).

Does this package have the AVX CPU extensions enabled? For example, my tiny Intel N3050 processor does not have them. Maybe, different packages depending on it could be released. 

If you provide a FreeBSD 12.2 package I will be pleased to test it. 

Many thanks.

**Comment by psa** [comment]
Unfortunately, I only build for my servers and they're all FreeBSD 13.0 with AVX (but not AVX2). If someone builds 12.2 packages and wants them hosted in the same place, I'm happy to attach them to my releases page.

**Comment by dml33** [comment]
How do you build the txz package? Is there any script? In the Makefile I do not see any package section. 
Thanks

**Comment by psa** [comment]
@dml33

```
cd /usr/ports/www
git checkout https://github.com/huo-ju/photoprism-freebsd-port photoprism
cd photoprism
make package
```

The package should then be in the `work` directory.

The better way to do it is to use poudriere, it takes a little more configuration and you can find several guides, such as this one https://danschmid.de/en/blog/poudriere-guide

If you want to use that, then you'll need to checkout this repository in the poudriere ports directory (e.g. `/usr/local/poudriere/ports/default/www/photoprism`) and then run `poudriere bulk -j <poudriere jail name> www/photoprism`

**Comment by dml33** [comment]
> @dml33
> 
> ```
> cd /usr/ports/www
> git checkout https://github.com/huo-ju/photoprism-freebsd-port photoprism
> cd photoprism
> make package
> ```
> 
> The package should then be in the `work` directory.
> 
> The better way to do it is to use poudriere, it takes a little more configuration and you can find several guides, such as this one https://danschmid.de/en/blog/poudriere-guide
> 
> If you want to use that, then you'll need to checkout this repository in the poudriere ports directory (e.g. `/usr/local/poudriere/ports/default/www/photoprism`) and then run `poudriere bulk -j <poudriere jail name> www/photoprism`

I have just built the 20210505 package for FreeBSD 12.2 and non AVX CPUs. How can I send it to you?

**Comment by psa** [comment]
@dml33 I have sent you a collaboration request, once you accept you should be able to upload to the repository directly.

**Comment by dml33** [comment]
@psa Thanks! I have just uploaded my package as a new release.
Just as suggestion, I like the style used for releases for Emby-server, for example:
https://github.com/MediaBrowser/Emby.Releases/releases
There, under the same Release, there are differente packages, for differente platforms and flavours. 
In this case, under the 20210505 release, we could place both the FreeBSD 13.0 and FreeBSD 12.2-noAVX packages.
Do as you wish, of course.

Thank you for letting me collaborate with you.

**Comment by psa** [comment]
@dml33 Great idea, thanks. Fixed.

**Comment by psa** [comment]
@huo-ju I believe this can be closed.

**Comment by dml33** [comment]
@psa I have just finished compiling g20210523. I am uploading the g20210523 package for FreeBSD 12.2 and no-AVX CPU extensions to your repository.
Thanks to you both!
