### ISSUE TITLE
Add releases

### ISSUE THREAD

**Issue by psa** [huo-ju/photoprism-freebsd-port#17]
Until this can be pushed into the ports tree, I think it'd be good for us to provide pre-built releases for those who want them.

I've done so on my branch https://github.com/psa/photoprism-freebsd-port/releases, but I think it'd be nice to do so here to centralise.

**Comment by psa** [comment]
Fixed in #18

**Comment by huo-ju** [comment]
Thanks.

**Comment by psa** [comment]
Having them in my repo is less discoverable than having them attached here. I think they should be attached to this project, what do you think?

If that's not of interest to you, do you think we should add a link to the README to point to my repo?

**Comment by huo-ju** [comment]
Good idea. I just add a link  https://github.com/huo-ju/photoprism-freebsd-port/commit/b7cb5c8c4e0a7929a29189823655229ad088c0e8 to your repo. Thanks.
