### ISSUE TITLE
darktable or rawtherapee won't convert anyting, trying to write to /.config or /.cache

### ISSUE THREAD

**Issue by chaosbiber** [huo-ju/photoprism-freebsd-port#20]
I have a lot of raws that photoprism alone couldn't handle so I installed **rawtherapee** and **darktable** via pkg into my FreeBSD 12.2 Jail (on TrueNAS Core). They're then magically called from the photoprism service installed by that port, but both cli tools apparently try to access `/.config` in the root (not /root) folder and fail. I modified the created photoprism user by adding a home directory and shell, also adding `photoprism_chdir="/home/photoprism"` in `/usr/local/etc/rc.d/photoprism`, but still they try `/.config`. Creating `/.config` and `/.cache` under `/` and giving the photoprism user permissions _does_ work, but I think there should be a better solution, even in a jail.

Error message: `"index: failed converting DSCxxxxx.ARW to jpeg (path lookup '/.config/darktable' fails with: 'No such file or directory'\n)"`

Unsure if it's a photoprism or port problem, but I don't think photoprism calls those tools explicitly from '/' and someone with more FreeBSD knowledge then me could point out the original problem?

photoprism has an environment variable to set the paths for rawtherapee or darktable, so another workaround would be a wrapper script. But in the case of darktable the `--core --configdir` option has to come after other parameters I think.

Thanks for the port, it's great!

**Comment by ltning** [comment]
`export XDG_CONFIG_HOME=<path>` in `/usr/local/etc/rc.d/photoprism` just before the last line (`run_rc_program "$1"`) takes care of this issue. I'm sure it could have a default where if not already set, default to somewhere like `${photoprism_storagepath}/.config`.

**Comment by chaosbiber** [comment]
Thanks, adding that line works for me.

**Comment by perplexa** [comment]
Just adding here in case somebody else stumbles across the same issue. For me, even after adding `XDG_CONFIG_HOME` darktable kept failing as it is trying to write to `/.cache` as well.

Adding the following lines to `/usr/local/etc/rc.d/photoprism` solved this for me:

```
export XDG_CONFIG_HOME="${photoprism_storagepath}/.config"
export XDG_CACHE_HOME="${photoprism_storagepath}/.cache"
```
