### ISSUE TITLE
Photo prism does not build cleanly on FreeBSD 12.2-RELEASE-p6

### ISSUE THREAD

**Issue by quistian** [huo-ju/photoprism-freebsd-port#21]
I am trying to compile PhotoPrism in a TrueNAS jail, which is running FreeBSD 12.2-RELEASE-p6

The error messages are:

>>> defined at deflate.c
>>>            deflate.pic.o:(.text.deflateParams+0x0) in archive bazel-out/host/bin/external/zlib_archive/libzlib.pic.a

ld: error: too many errors emitted, stopping now (use -error-limit=0 to see allerrors)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow:libtensorflow.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.924s, Critical Path: 7.26s
INFO: 6 processes: 6 local.
FAILED: Build did NOT complete successfully
*** Error code 1

**Comment by psa** [comment]
Do you have the full build logs to share?

If you want pre-built binaries, check out https://github.com/psa/photoprism-freebsd-port/releases/tag/2021-05-23

**Comment by quistian** [comment]
Where's the location of the build logs? 

>   java.log.photoprism.root.log.java.20210723-073639.7319

I can try the prebuilt binaries and get back to you.

**Comment by psa** [comment]
I suspect the relevant part is `C++ compilation of rule '//tensorflow/core/kernels:matrix_square_root_op' failed (Killed)`

`Killed` often means running out of RAM (it could also be a few other things, like running out of file handles etc). How much does that machine have and how much is free?

Are you building it with poudriere (highly recommended)?

If so, consider using `USE_TMPFS=no`. You may also need to play with `MAX_MEMORY` (I use 8, which is 25% of the RAM on my build machine). If you have other things building at the same time in the same job, then setting `PARALLEL_JOBS=1` may help.

**Comment by quistian** [comment]
Thanks. I am running it in a jail using TrueNAS. I can try the poudriere methodolgy.

**Comment by ascl00** [comment]
I am also using TrueNAS, and not using poudriere, and have found applying this patch necessary (at least for the duplicate symbol issue):
https://github.com/tensorflow/tensorflow/issues/31196#issue-475147706

For the killed issue, I found editing the Makefile and adding the following to the bazel command helped:
--jobs 1 --local_resources 2048,0.5,1.0

(my NAS has 32GB of RAM too, but I guess zfs is just RAM hungry!). Between these two I have a successful build on TrueNAS now.

**Comment by huo-ju** [comment]
@ascl00 Thanks.  It has been fixed now. https://github.com/huo-ju/photoprism-freebsd-port/commit/0f2436976649da5ad7aef70e233388bd53f5b482
