### ISSUE TITLE
p5-Image-ExifTool package is needed as dependency

### ISSUE THREAD

**Issue by dml33** [huo-ju/photoprism-freebsd-port#22]
Hi.

I have just discover that p5-Image-ExifTool package is needed as a dependency in the port, so exiftool command can be invoked by PhotoPrism and EXIF data is retrieved from videos.

The whole discussion is [here](https://github.com/photoprism/photoprism/issues/1447). 

`You need to have exiftool installed. I was assuming you run our Docker image which comes with exiftool pre-installed.`

`PhotoPrism supports Exif natively, without Exiftool. Videos however don't use Exif but other standards.`

Only after installing this package and re-import or re-index the library, video details were taken by PhotoPrism and shown correctly in the UI.

Could you please add it?

Thanks!

**Comment by huo-ju** [comment]
Thanks, `p5-Image-ExifTool` has been add to the `RUN_DEPENDS`.
