### ISSUE TITLE
problems in compiling under freebsd - file missing

### ISSUE THREAD

**Issue by chris-x-tra** [huo-ju/photoprism-freebsd-port#23]
I have the following issue - can you please provide the file

root@calcit:/home/chrissie/photoprism-freebsd-port # make install
===>  Patching for photoprism-g20210523
===>  Applying extra patch /usr/home/chrissie/photoprism-freebsd-port/files/extra-patch-docker_tensorflow_tensorflow-1.15.2_third_party_repo.bz
cat: /usr/home/chrissie/photoprism-freebsd-port/files/extra-patch-docker_tensorflow_tensorflow-1.15.2_third_party_repo.bz: No such file or directory
===>  FAILED Applying extra patch /usr/home/chrissie/photoprism-freebsd-port/files/extra-patch-docker_tensorflow_tensorflow-1.15.2_third_party_repo.bz
*** Error code 1

**Comment by huo-ju** [comment]
Sorry for the typo. It has been fixed now.
