### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by defilor** [huo-ju/photoprism-freebsd-port#24]
Hi, I'm having some issues with permissions, first of all either the storage or assets folder that is created had the wrong permissions set which prevented the service from starting, it was assigned to root:photoprism iirc. Secondly, and that is giving me more trouble right now, I can't upload any images as it seems the database is read-only. Not sure how I can solve that manually, would need detailed instructions for that as I know nothing about databases. 

Also can't seem to set the storage, assets and import folder permanently, have to resort to setenv for this. Is there a solution?

Thanks for all the effort!

**Comment by huo-ju** [comment]
The install script should create the ```photoprism:photoprism``` group/user. and the rc script will be run under photoprism:photoprism 

Please see this line for more details : https://github.com/huo-ju/photoprism-freebsd-port/blob/432417f2661a098b9a605ba123b250fb01c4a653/files/pkg-install.in#L9

You may try to set the ownership of ```${photoprism_storagepath}``` as ```photoprism:photoprism```  ?
