### ISSUE TITLE
update freebsd-port to latest photoprism release 210925-96168e4b

### ISSUE THREAD

**Issue by dml33** [huo-ju/photoprism-freebsd-port#25]
Hi.

Would it be possible to update [photoprism-freebsd-port](https://github.com/huo-ju/photoprism-freebsd-port) to latest photoprism release [210925-96168e4b](https://github.com/photoprism/photoprism/releases/tag/210925-96168e4b)?

There are some fixes going on since then, but it would great to be able to test the new face detection feature.

Thanks!

**Comment by huo-ju** [comment]
Done. Thanks.
