### ISSUE TITLE
facenet model is missing in the asset path

### ISSUE THREAD

**Issue by dml33** [huo-ju/photoprism-freebsd-port#26]
Hi.

I compiled the [210925-96168e4b](https://github.com/huo-ju/photoprism-freebsd-port/commit/58bbd7522ffe7501d402690fb48ffee8a5b42913), but after a complete rescan, no People are found in the People section.

I opened a [discussion](https://github.com/photoprism/photoprism/discussions/1584) in Photoprism about it. It seems that the docker image is not complete and the facenet model is missing in the asset path. 

Could you please check it?

Thanks!

**Comment by huo-ju** [comment]
Thanks. It has been fixed. 432417f2661a098b9a605ba123b250fb01c4a653

You can also download the model from [https://dl.photoprism.org/tensorflow/facenet.zip](https://dl.photoprism.org/tensorflow/facenet.zip) and unzip it, then copy the ```aved_model.pb``` to ```/var/db/photoprism/assets/facenet/```.

Sorry for the inconvenience.

**Comment by dml33** [comment]
Hi.

PhotoPrism mantainers are asking here [issue 1584](https://github.com/photoprism/photoprism/discussions/1584)

` Should do this by ourselves in the future. What's the process?`

Could you confirm them what to do?

Thanks!
