### ISSUE TITLE
Photoprism version date is set to compilation date

### ISSUE THREAD

**Issue by dml33** [huo-ju/photoprism-freebsd-port#34]
Hi.

Every time I compile a Photoprism port, the date which appears at the footer, together with the git commit hash, is the compilation date, not the original one of the git tag.

For example, for the g20220118 and tag name 76c94a1f38896d6bb79c4bbe7266a55edbc43862, instead of appearing the original tag date, which is 20220118, it appears as the date I compiled it: 20220119. 

![image](https://user-images.githubusercontent.com/25033130/150300340-35063291-8d95-4343-a4de-1a5a5e83c3e3.png)

It happens with all your Photoprism ports I have compiled.

I wanted to ask if this behavior comes to your port side or it is in photoprism code itself instead. It is just a matter of coherence, to avoid confusion about which tag it is really, without entering to check the hash with the git repository.

Thanks!

**Comment by huo-ju** [comment]
Photoprism's build script will generate the version tag. So the `220119` is the time that you built the port. 

Please see this line:

https://github.com/photoprism/photoprism/blob/4dd09f45023d9ae27b340008fb4ce7576a8b6801/scripts/build.sh#L5

**Comment by dml33** [comment]
@lastzero Wouldn't be much more appropriate to have in `PHOTOPRISM_DATE` the date of the git commit instead of the compilation date?
Thanks!

**Comment by huo-ju** [comment]
@dml33 We can replace the `PHOTOPRISM_DATE` in the port, that's not a problem. But the git commit hash has indicated the commit date, IMO. Can I ask the reason that you want include commit date in the version string?

**Comment by lastzero** [comment]
Because dependencies are not statically included in the repository. Downloading the "same" package a few days later could result in differences. Updated dependencies won't change the last commit hash.

**Comment by dml33** [comment]
> @dml33 We can replace the `PHOTOPRISM_DATE` in the port, that's not a problem. But the git commit hash has indicated the commit date, IMO. Can I ask the reason that you want include commit date in the version string?

It's just a coherence issue.
 
For example, in the Photoprism release web https://github.com/photoprism/photoprism/releases, releases are listed ordered by release date together with their hash.

However, when I can compile the port, some days have passed. Thus, the hash is kept, but the day is not the release date, but the compilation date. 

When I enter my Photoprism server, at the footer, the compilation date is shown together with the hash

![image](https://user-images.githubusercontent.com/25033130/150653517-84737d4e-ebec-43e2-ae2b-86b2201046c7.png)


Then, that date and hash cannot be traced to the Photoprism release page, and the user could doubt which is right: the hash or the date or if that compilation is altered somehow and it is not the official release.

I think that release date and hash must be kept together and the same as the PhotoPrism release ones, in order to show coherence and safety.

**Comment by huo-ju** [comment]
@dml33  Understood.  So how about this format: 

``{commit hash}-build-{build_date}``

example:

``76c94a1f38896d6bb79c4bbe7266a55edbc43862-build-20220122``

It's a straightforward solution, imo.

**Comment by dml33** [comment]
Hi, 

In PhotoPrism demo page https://demo.photoprism.app/settings, with [January 21, 2022 release](https://github.com/photoprism/photoprism/releases/tag/220121-2b4c8e1f), it is this way
![image](https://user-images.githubusercontent.com/25033130/150680898-4e59eea6-b95b-4866-abf1-8f4be7ff9d38.png)

Then, what about 
`{release tag date}-{release tag hash}-{O.S}-{arch}-build-{build date}`

My only doubt is that currently, the port shows the long hash of the release tag, but PhotoPrism demo shows the short one. Also, PhotoPrism demo only shows the year with 2 numbers, instead of 4, but I think that that is not very important

For example, in our case:
`220118-76c94a1f38896d6bb79c4bbe7266a55edbc43862-FreeBSD-arm64-build-20220122`

`220118-76c94a1-FreeBSD-arm64-build-20220122`

`220118-76c94a1-FreeBSD-arm64-build-220122`

What do you think?

**Comment by huo-ju** [comment]
@dml33  ```220118-76c94a1-FreeBSD-amd64-DEBUG-build-220122``` should be a good version string. I will implement it in the next release. Thanks.
