### ISSUE TITLE
Service started but cannot get into the application: No login screen

### ISSUE THREAD

**Issue by gvelim** [huo-ju/photoprism-freebsd-port#37]
This relates to an upgrade from the previous version that was working as expected.
Compiled successfully and re-installed `photoprism-g20220302`. 
I am using MariaDB as a backend.

I started the service and when I went to the photoprism URL I got just this

![image](https://user-images.githubusercontent.com/3185416/159462069-a531fbe0-d062-46d2-871e-065da5a547b4.png)

When I look at /var/log/messages there is an error about `assets.json`

```
Mar 22 10:03:41 photoprism photoprism[28815]: time="2022-03-22T10:03:41Z" level=info msg="PhotoPrism® needs your support!"
Mar 22 10:03:41 photoprism photoprism[28815]: time="2022-03-22T10:03:41Z" level=info msg="Visit https://docs.photoprism.app/funding/ to learn more."
Mar 22 10:03:47 photoprism photoprism[28815]: time="2022-03-22T10:03:47Z" level=info msg="config: read-only mode enabled"
Mar 22 10:03:47 photoprism photoprism[28815]: time="2022-03-22T10:03:47Z" level=info msg="http: enabling gzip compression"
Mar 22 10:03:47 photoprism photoprism[28815]: time="2022-03-22T10:03:47Z" level=info msg="webdav: server disabled"
Mar 22 10:03:47 photoprism photoprism[28815]: time="2022-03-22T10:03:47Z" level=info msg="http: starting web server at 0.0.0.0:2342"
Mar 22 10:03:49 photoprism photoprism[28815]: time="2022-03-22T10:03:49Z" level=error msg="frontend: cannot read assets.json"
Mar 22 10:03:50 photoprism photoprism[28815]: time="2022-03-22T10:03:50Z" level=error msg="frontend: cannot read assets.json"
```
Environment variables in `rc.conf` are set as expected given this setup was working fine until upgraded.

Any ideas how to fix this ?

**Comment by llmII** [comment]
@gvelim - see the diff in #36

edit the port then rebuild, must have the edits for the Makefile and pkg-plist, the remaining edit is optional.

I had the same issue and doing all that got me back a working version.

**Comment by gvelim** [comment]
fixed.. response in #36
