### ISSUE TITLE
Update port to 220517 PhotoPrism Release

### ISSUE THREAD

**Issue by dml33** [huo-ju/photoprism-freebsd-port#38]
Hi.

Could you update the port to fetch and compile release 220517 of PhotoPrism?

https://github.com/photoprism/photoprism/releases/tag/220517-b9c68f8f

Thanks!

**Comment by huo-ju** [comment]
Sure, I'm working on it. Their build script has changed a lot, so it need more time to upgrade the port. Sorry for this.

**Comment by huo-ju** [comment]
I'm sorry it will take more time to upgrade. Our city was hit by a
thunderstorm, and the power in my area still not restore. It may take days
to fully restore.

**Comment by huo-ju** [comment]
done @https://github.com/huo-ju/photoprism-freebsd-port/commit/8da8ea799b4c2e6e2ffbbc6d747d8c76cd53d05e
