### ISSUE TITLE
Document setting admin password

### ISSUE THREAD

**Issue by danb35** [huo-ju/photoprism-freebsd-port#4]
Unless there's a default password set somewhere that I can't find (I see "photoprism" in `docker-compose.yml`, but it doesn't work), the admin password doesn't seem to be set--and there needs to be a password there for admin to log in.  A simple `photoprism passwd`, as mentioned in the photoprism docs, doesn't work, as it's unable to locate its assets directory.  To set the password, after installing `sudo` if needed, the user can run `sudo -u photoprism /usr/local/bin/photoprism --assets-path=/var/photoprism/assets --storage-path=/var/photoprism/storage --originals-path=/var/photoprism/storage/originals --import-path=/var/photoprism/storage/import passwd`, substituting `/var/photoprism/assets` and `/var/photoprism/storage` with their assets and storage paths, respectively.

Edit: or `su -m photoprism -c '/usr/local/bin/photoprism ...'`, which doesn't require `sudo` to be installed.

**Comment by huo-ju** [comment]
done. Thanks.
