### ISSUE TITLE
Update to PhotoPrism June 29, 2022

### ISSUE THREAD

**Issue by dml33** [huo-ju/photoprism-freebsd-port#40]
Hi.

Could you please update the port to fetch and compile release 220629-5d7448d2 of PhotoPrism?

https://github.com/photoprism/photoprism/releases/tag/220629-5d7448d2

Many thanks!

**Comment by huo-ju** [comment]
Done. https://github.com/huo-ju/photoprism-freebsd-port/commit/ac11a7457800d49225ac0ea5c4c7813265916770
