### ISSUE TITLE
Make Config Failure

### ISSUE THREAD

**Issue by EmperorMurfy** [huo-ju/photoprism-freebsd-port#41]
Hello! So I tried installing Photoprism into TrueNAS core and it didn't exactly work. Now since TrueNAS core is based on FreeBSD, most people directed me here to install it. I've tried to do this in a clone jail shell and just normal shell in the ui, but it simply didn't work. 

The git clone worked most of the time, but I couldn't execute make config or make && make install. It just simply didn't work and gave me an error. I don't know what I've done wrong. 

I've attached a screenshot to the error I get down below.
![Screenshot 2022-08-08 193208](https://user-images.githubusercontent.com/110864180/183531935-ebeda554-9381-4def-bb50-86ce1d3a2a0e.png)

**Comment by EmperorMurfy** [comment]
I am happy to help if you need me to be more specific in certain area's to help solve this bug.

**Comment by huo-ju** [comment]
Do you have a copy of ports installed? Try to run `ls /usr/ports/Mk/` in the jails. You can use `portsnap fetch extract` to get the port tree if there are no files.

**Comment by EmperorMurfy** [comment]
I'll try to do that. I'll keep you posted!

**Comment by EmperorMurfy** [comment]
I could not run ls /usr/port/Mk as it said there was no files. So, I ran portsnap fetch extract which did in fact run and completed without error.

**Comment by EmperorMurfy** [comment]
Make config did basically nothing but it didn't result in an error. Make && make install did run and had some gui's which I just resulted to default and didn't touch anything.

**Comment by huo-ju** [comment]
@EmperorMurfy Thanks for the reminder. The `make config` should be remove from the README. The `make config` is using for set the options to build the `tensorflow` in the previous releases, but we depends on the official libtensorflow ports instead of build it by ourself.

The README has been updated.

**Comment by EmperorMurfy** [comment]
BTW, I used nano to edit rc.conf. Is that ok?

**Comment by EmperorMurfy** [comment]
I'm kinda stuck now. I put in everything for rc.conf and saved it. I then tried setting up a password by pasting the line into shell and didn't do much and didn't run. I then tried running photoprism, which just said photoprism does not exist in /etc/rc.d or the local startup

Directories (/usr/local/etc/rc.d), or is not executable

**Comment by huo-ju** [comment]
Did you run the command `make install` successful?  The photoprism should be build and install to `/usr/local/bin/photoprism`, then you can setup the password, and you can run `photoprism` directly.

**Comment by EmperorMurfy** [comment]
Yes, I did run it successfully

**Comment by EmperorMurfy** [comment]
When I do ls /usr/local/bin/photoprism it just say's no such file or directory

**Comment by EmperorMurfy** [comment]
I think after the download and install, I start running into issues. I edited the config with nano and just copied and pasted this  into rc.config: photoprism_enable="YES"
photoprism_assetspath="/var/db/photoprism/assets"
photoprism_storagepath="/var/db/photoprism/storage"


I didn't rly know where to put the password (fresh install) code so I just entered into into a the jail's shell and did nothing. 

service photoprism start - had an error. Screenshot include
<img width="694" alt="Screen Shot 2022-08-09 at 5 47 30 PM" src="https://user-images.githubusercontent.com/110864180/183792531-750d8510-5dda-49f2-b85d-46ddee0dd9fb.png">
d

**Comment by EmperorMurfy** [comment]
Do you mind running me through how to install this into truenas core jails? I want to compare it with my current understanding of how to install this. Perhaps I did something wrong in the installation instead of the code being broken.

**Comment by huo-ju** [comment]
There are no different between this port and other ports, just install the [libtensorflow1](https://www.freshports.org/science/libtensorflow1/) from official port tree, then `make` this ports, then `make install` if the build successful. 

You may like to install the pre-build release: https://github.com/psa/photoprism-freebsd-port/releases

**Comment by EmperorMurfy** [comment]
How can I install the pre-build release? Please be patient with me as I am new to github and freebsd (truenas core)

**Comment by EmperorMurfy** [comment]
Would it be possible for you to make a .json file of this? Like something like these files: https://github.com/ix-plugin-hub/iocage-plugin-index

**Comment by EmperorMurfy** [comment]
How can I fetch the pre-build release? I did: fetch https://github.com/psa/photoprism-freebsd-port/releases and it didn't work.

**Comment by huo-ju** [comment]
Just download the pkg file, and use the `pkg add` command to install it locally. 

Please read the FreeBSD document. https://www.freebsd.org/cgi/man.cgi?pkg-add(8)
