### ISSUE TITLE
Error when changing rc command_arg to use a options.yml file

### ISSUE THREAD

**Issue by reyman** [huo-ju/photoprism-freebsd-port#42]
Hi, 
First, thanks for your work on this ports.

I'm using it with some modification into `/usr/local/etc/rc.d/photoprism`, i found this is more easy to pass a `options.yml` that override all defaults i need. 

So i change the photoprism command_args with something simpler : 
`photoprism --defaults-yaml=/usr/local/etc/photoprism/options.yml --trace start `

And options.yml 

```
HttpPort: 2342
HttpHost: 127.0.0.1
debug: true

AssetsPath: /data/photoprism/assets
ConfigPath: /usr/local/etc/photoprism
StoragePath: /data/photoprism/storage
OriginalsPath: /data/photoprism/storage/originals
ImportPath: /data/photoprism/storage/imports

AdminPassword: xxx
```

But i have an error of template at running, i link to [the discussion with photoprism here](https://github.com/photoprism/photoprism/discussions/2679), that also contain more detail about the BastilleFile i used to run photoprism in jail.

It seems static file missing.

Thanks for your help !

**Comment by huo-ju** [comment]
Thanks, I will add the `defaults-yaml` in the next release, as well as fix the static files issues.

**Comment by huo-ju** [comment]
done @ c0f0a678c7b7673b32e7d1f588097631aa75a4d2
