### ISSUE TITLE
heif-convert binary is missing

### ISSUE THREAD

**Issue by jan666** [huo-ju/photoprism-freebsd-port#45]
The port does not install the heif-convert binary. It is needed to have support for HEIC files (e. g. iPhones). It skippes silently if the binary is not found. 

Added in Pull Request 44

**Comment by jan666** [comment]
Btw: its almost impossible to "fix" the database later. You have to remove the originals and run purge and cleanup multiple times. I just started a fresh restart because I have 7 years of live photos

**Comment by huo-ju** [comment]
Thanks, the PR has been merged.

Sorry for the inconvenience to restart your photos.
