### ISSUE TITLE
libtensorflow1 dependency via FreshPorts broken

### ISSUE THREAD

**Issue by lispstudent** [huo-ju/photoprism-freebsd-port#46]
Hello,

Just to let you know, at the moment the [libtensorflow1](https://www.freshports.org/science/libtensorflow1/) dependency on FreshPorts is broken, so `photoprism` cannot be installed using ports or from the prebuilt binary.

**Comment by jan666** [comment]
Hi,

you can use a pkg package from here: https://github.com/psa/libtensorflow1-freebsd-port - that works for me.

**Comment by lispstudent** [comment]
Ah, I see it is [already being dealt with](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=266130). Sorry for the noise.

**Comment by lispstudent** [comment]
Thanks @jan666 I will do that.

**Comment by lispstudent** [comment]
PS: Thank you so much for the port!
