### ISSUE TITLE
GO error when compiling

### ISSUE THREAD

**Issue by vanyolai** [huo-ju/photoprism-freebsd-port#47]
Hello, I wonder if anyone else has the same problem... The compiler quits with an error:
`===>  photoprism-g20220901 USES=go has invalid arguments: 1.19.
*** Error code 1

Stop.`
My Go version is 1.19.2 
Thanks!

**Comment by huo-ju** [comment]
Can you paste the line of `GO_VALID_VERSIONS` in the  `/usr/ports/Mk/Uses/go.mk`?

The correct value should be  `GO_VALID_VERSIONS=	1.18 1.19 1.20-devel`

**Comment by vanyolai** [comment]
No such a line in the go.mk file.
$FreeBSD: head/Mk/Uses/go.mk 566511 2021-02-24 22:39:56Z dmgk

**Comment by vanyolai** [comment]
I did a 
`portsnap fetch`
`portsnap extract`
`portsnap update`
and now the go.mk is the right version with `GO_VALID_VERSIONS= 1.18 1.19 1.20-devel`
and the build was successfull. Thanks for helping me out!
