### ISSUE TITLE
Registering installation step failing

### ISSUE THREAD

**Issue by fafafabien** [huo-ju/photoprism-freebsd-port#48]
Hi,

First of all thanks for the port, greatly appreciated!

I am encountering a make issue at the end of the process on my freebsd 13.1:

===>   Registering installation for photoprism-g20220901
pkg-static: Unable to access file /usr/ports/www/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/facenet/saved_model.pb:No such file or directory
pkg-static: Unable to access file /usr/ports/www/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/facenet/version.txt:No such file or directory
pkg-static: Unable to access file /usr/ports/www/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nasnet/labels.txt:No such file or directory
pkg-static: Unable to access file /usr/ports/www/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nasnet/saved_model.pb:No such file or directory
pkg-static: Unable to access file /usr/ports/www/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nasnet/variables/variables.data-00000-of-00001:No such file or directory
pkg-static: Unable to access file /usr/ports/www/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nasnet/variables/variables.index:No such file or directory
pkg-static: Unable to access file /usr/ports/www/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nasnet/version.txt:No such file or directory
pkg-static: Unable to access file /usr/ports/www/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nsfw/labels.txt:No such file or directory
pkg-static: Unable to access file /usr/ports/www/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nsfw/saved_model.pb:No such file or directory
pkg-static: Unable to access file /usr/ports/www/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nsfw/variables/variables.data-00000-of-00001:No such file or directory
pkg-static: Unable to access file /usr/ports/www/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nsfw/variables/variables.index:No such file or directory
pkg-static: Unable to access file /usr/ports/www/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nsfw/version.txt:No such file or directory
pkg-static: Unable to access file /usr/ports/www/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/facenet/:No such file or directory
pkg-static: Unable to access file /usr/ports/www/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nasnet/variables/:No such file or directory
pkg-static: Unable to access file /usr/ports/www/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nasnet/:No such file or directory
pkg-static: Unable to access file /usr/ports/www/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nsfw/variables/:No such file or directory
pkg-static: Unable to access file /usr/ports/www/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nsfw/:No such file or directory
*** Error code 1

Stop.
make: stopped in /usr/ports/www/photoprism-freebsd-port

Any clue what I am missing?

Fabien

**Comment by huo-ju** [comment]
Hi, It looks like something wrong during the model download task. 

Please see this line about the download. https://github.com/huo-ju/photoprism-freebsd-port/blob/e8b2810ca2d25b3c4b39ab2bb7b0de1a7ab23bb4/Makefile#L43 

Did you see any errors after `make`?

**Comment by fafafabien** [comment]
Hi, thanks a lot for the hint, should I have seen that by self!
Indeed the 3 .zip downloads failed because the '--inet4-only' option isn't recognized, see extract below:

------------------------------------------------
Installing Facenet model for TensorFlow...
Downloading latest model from https://dl.photoprism.app/tensorflow/facenet.zip?20221030...
wget: unrecognized option '--inet4-only'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
shasum: /tmp/photoprism/facenet.zip: No such file or directory

unzip: Failed to open '/tmp/photoprism/facenet.zip'
./scripts/download-facenet.sh: line 44: assets/facenet/version.txt: No such file or directory
Latest Facenet installed.
------------------------------------------------

I just downloaded manually the 3 zip and put them when the script expect them and all went like a charm.

I guess you need to do quick fix on the wget calls used in the Makefile, I won't take the risk to mess that up so I am leaving it to you!

Thx again,

Fabien

**Comment by fafafabien** [comment]
Sure, sounds good to me.
It would be nicer to have the script compiling properly without having to manually intervene. 
Also I closed/reopened the issue as running a "portupgrade -a" I had the impression the pb was corrected but it is still there, sorry :-)

**Comment by huo-ju** [comment]
fixed @ https://github.com/huo-ju/photoprism-freebsd-port/commit/1bf2a4041e7ef695a6db0e21cf30272c2f6c1584  the `wget` dependency set to 1.21+
