### ISSUE TITLE
Update port to Release 221118-e58fee0fb

### ISSUE THREAD

**Issue by dml33** [huo-ju/photoprism-freebsd-port#49]
Hi.

Is it possible to update the port to latest release 221118-e58fee0fb?

https://github.com/photoprism/photoprism/releases/tag/221118-e58fee0fb

Thank you very much

**Comment by huo-ju** [comment]
done @ https://github.com/huo-ju/photoprism-freebsd-port/commit/1bf2a4041e7ef695a6db0e21cf30272c2f6c1584

**Comment by 5ch17** [comment]
@dml33 @psa -- are you still maintaining the binaries repo? Is it possible to post a binary for the latest version(s) of PhotoPrism such as https://github.com/photoprism/photoprism/releases/tag/230719-73fa7bbe8? Also, is this able to be compiled under Freebsd 13.2 release?

**Comment by tinsukE** [comment]
> Is it possible to post a binary for the latest version(s) of PhotoPrism such as https://github.com/photoprism/photoprism/releases/tag/230719-73fa7bbe8?

That is already the case: https://github.com/huo-ju/photoprism-freebsd-port/pull/59

**Comment by 5ch17** [comment]
> That is already the case: #59

Thank you @tinsukE . Would you please confirm the FreeBSD release you are using for this (12.4 or 13.2) and version of libtensorflow you use?

**Comment by tinsukE** [comment]
I compile `libtensorflow1` and `photoprism` myself and run, all on 13.2 jails.

For `libtensorflow1`  (latest 1.15.5_2) I use the port linked on the `README.md`: https://github.com/huo-ju/photoprism-freebsd-port#dependencies

**Comment by dml33** [comment]
Hi.

Sorry for the delay. 

I have just uploaded the g20230719 release for FreeBSD 12.3:

https://github.com/psa/photoprism-freebsd-port/releases

Currently, I am still using FreeBSD 12.3. I want to upgrade my NAS to 13.x soon, but I cannot find enough free time to do it. I am sure it will not be as smooth as it would be 👯 As soon as I do it, I will go on publishing the binaries for the FreeBSD 13.x branch.

Regards

**Comment by lapo-luchini** [comment]
I'm building binary package for FreeBSD 13.2/amd64 for myself, if anyone wants I just uploaded it [on my fork release page](https://github.com/lapo-luchini/photoprism-freebsd-port/releases).

**Comment by 5ch17** [comment]
> I'm building binary package for FreeBSD 13.2/amd64 for myself, if anyone wants I just uploaded it [on my fork release page](https://github.com/lapo-luchini/photoprism-freebsd-port/releases).

were you able (and if yes, how - poudriere, ports, what dev stack tools installed) to build libtensorflow1 under 13.2? I cannot get past an error when trying in a 13.2 jail:

ERROR: /usr/ports/science/libtensorflow1/work-default/tensorflow-1.15.5/tensorflow/core/BUILD:2724:1: ProtoCompile tensorflow/core/framework/allocation_description.pb.h failed (Illegal instruction): protoc failed: error executing command bazel-out/host/bin/external/com_google_protobuf/protoc '--cpp_out=bazel-out/host/bin' -I. -I. -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src ... (remaining 3 argument(s) skipped)
ERROR: /usr/ports/science/libtensorflow1/work-default/tensorflow-1.15.5/tensorflow/core/BUILD:2747:1 ProtoCompile tensorflow/core/framework/allocation_description.pb.h failed (Illegal instruction): protoc failed: error executing command bazel-out/host/bin/external/com_google_protobuf/protoc '--cpp_out=bazel-out/host/bin' -I. -I. -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src ... (remaining 3 argument(s) skipped)
INFO: Elapsed time: 0.907s, Critical Path: 0.03s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
*** Error code 1

**Comment by lapo-luchini** [comment]
I don't remember having problems compiling it, but it was a while ago. It's possible that it no longer compiles with more recent dependencies. I will upload my package for that too.

**Comment by 5ch17** [comment]
Thank you @lapo-luchini @dml33 and @tinsukE for your updates/binaries. Was able to install photoprism 2023-07-19 package compiled by @lapo-luchini for FreeBSD 13.2-release and libtensorflow1 from @psa repo (https://github.com/psa/libtensorflow1-freebsd-port/releases/tag/1.15.5-pre-release-0). Will report back if there are any functionality issues once I test the install.

**Comment by 5ch17** [comment]
> I don't remember having problems compiling it, but it was a while ago. It's possible that it no longer compiles with more recent dependencies. I will upload my package for that too.

@lapo-luchini -- would you please upload to your fork release page the binary for the photoprism latest release 230923 (for FreeBSD 13.2/amd64)? 

Still unable to compile this (not sure why, maybe it has to do with the jail on top of Truenas and not clean FreeBSD).

**Comment by lapo-luchini** [comment]
> binary for the photoprism latest release 230923

[Done](https://github.com/lapo-luchini/photoprism-freebsd-port/releases).
