### ISSUE TITLE
Assets folder permissions (and location)

### ISSUE THREAD

**Issue by lapo-luchini** [huo-ju/photoprism-freebsd-port#5]
The log doesn't seem to be working, so I launched the application using `sudo -u photoprism` and I see this error:

```
ERRO[2021-01-25T12:51:55+01:00] index: open /var/photoprism/assets/nasnet/labels.txt: permission denied
```

I guess this might be needed?

```
chgrp -R photoprism /var/photoprism/assets
```

Also, I'd suggest to move the assets folder in a different location, "straight under `/var` " is not the best place in [FreeBSD hierarchy](https://www.freebsd.org/cgi/man.cgi?hier(7)).

**Comment by huo-ju** [comment]
Thanks, I change the storage path to /var/db/photoprism to match the FreeBSD file system hierarchy.

6b0d94ff42fadccfe88c4d68744b9d3afea36e2f

For the permission, the install script should change the dir owner to ```photoprism```.

https://github.com/huo-ju/photoprism-freebsd-port/blob/c633676c4cf1721966d21f3c57ce618b227b178a/files/pkg-install.in#L36
