### ISSUE TITLE
Upgrade guidelines

### ISSUE THREAD

**Issue by mrcalvin** [huo-ju/photoprism-freebsd-port#50]
Hi!

Less of an issue report than a Q. First, thanks for the port, I am running it now a TrueNAS installation.

I am wondering: Are there any upgrade recommendations, guidelines from your end? Does a `git pull` & `make install` suffice?

Thx!

**Comment by jan666** [comment]
I'm just a user of this port but I think it should be:

### Download and Install

```
git clone https://github.com/huo-ju/photoprism-freebsd-port
cd photoprism-freebsd-port
make install clean
```

### Update

```
cd photoprism-freebsd-port
git pull
make reinstall clean
```

cleaning is important. If you dont clean you'll sometimes stuck with the old javascript-UI. So a `make clean` is never a mistake if something goes wrong.

**Comment by tinsukE** [comment]
Interesting, hadn't noticed the `reinstall` target.

I've been building packages (`package` target) on a separate jail (where I have all the dev packages installed), copying the file over to the PhotoPrism jail and installing it.

I'll make sure to clean things before creating a new package.

Thanks for the tip.
