### ISSUE TITLE
Node fails to install maplibre-gl

### ISSUE THREAD

**Issue by gizahNL** [huo-ju/photoprism-freebsd-port#51]
npm ERR! code 127
npm ERR! path /tmp/root/photoprism-freebsd-port/work/photoprism-e58fee0fb361715a1814cfd9d4577d3b9ad345e2/frontend/node_modules/maplibre-gl
npm ERR! command failed
npm ERR! command sh -c -- node ./postinstall.js
npm ERR! node ./postinstall.js: --: not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-04T10_30_46_471Z-debug-0.log
*** Error code 127

**Comment by huo-ju** [comment]
Can you paste the err log output from ` /root/.npm/_logs/2022-12-04T10_30_46_471Z-debug-0.log` ?
