### ISSUE TITLE
Cannot build: USES=go has invalid arguments: 1.19

### ISSUE THREAD

**Issue by gvelim** [huo-ju/photoprism-freebsd-port#52]
Hi, have cloned the repo and and on trying my first trying using `make -j8` I am getting

make -j8
===>  photoprism-g20221118 USES=go has invalid arguments: 1.19.
*** Error code 1

Stop.
make: stopped in /root/photoprism-freebsd-port

Have tried googling, with no luck. Reinstalled go119, same. 
Any pointers would be much appreciated

======
uname -a
FreeBSD photoprism 13.1-RELEASE-p2 FreeBSD 13.1-RELEASE-p2 n245412-484f039b1d0 TRUENAS amd64

pkg info go
go-1.19,2
Name           : go
Version        : 1.19,2
Installed on   : Tue Aug  9 15:04:39 2022 BST
Origin         : lang/go
Architecture   : FreeBSD:13:*
Prefix         : /usr/local
Categories     : lang
Licenses       : 
Maintainer     : go@FreeBSD.org
WWW            : https://golang.org
Comment        : Meta-port for the default version of the Go programming language
Annotations    :
	repo_type      : binary
	repository     : FreeBSD
Flat size      : 13.0B

**Comment by gvelim** [comment]
found previous closed issue

**Comment by girid333** [comment]
can you explain how was the issue solved ? facing the same error.

**Comment by gvelim** [comment]
https://github.com/huo-ju/photoprism-freebsd-port/issues/47#issuecomment-1284989864
