### ISSUE TITLE
Develop version of makefile 

### ISSUE THREAD

**Issue by reyman** [huo-ju/photoprism-freebsd-port#54]
Hi ! 

Do you think that could be possible to create a develop branch to test build of the latest version of photoprism ? 

There are 6 month between release on photoprism ...

Thanks !

**Comment by huo-ju** [comment]
You can use the makefile to build any branch. Just change the **GH_TAGNAME** to the commit hash you want to build.

https://github.com/huo-ju/photoprism-freebsd-port/blob/1bf2a4041e7ef695a6db0e21cf30272c2f6c1584/Makefile#L32

then run 'make makesum' to update the checksum file (distinfo).

**Comment by reyman** [comment]
@huo-ju Just a relative info, it seems a new release is out for photoprism : https://github.com/photoprism/photoprism/releases/tag/230504-cbf48798c
If you need a beta tester :)

**Comment by jan666** [comment]
@reyman see https://github.com/huo-ju/photoprism-freebsd-port/issues/55
