### ISSUE TITLE
Upgrade port to new version (230502-c405f6eff)

### ISSUE THREAD

**Issue by olenchenko** [huo-ju/photoprism-freebsd-port#55]
Hi and thank you so much for your great work!
Yesterday there was a major release of PhotoPrism (https://github.com/photoprism/photoprism/releases/tag/230502-c405f6eff) - do you plan to upgrade this port to the latest version?

Thanks again for your great work.

**Comment by jan666** [comment]
You can just edit the Makefile

```
[...]
DISTVERSION=   g20230504
[...]
GH_TAGNAME=     cbf48798c914ee9bfcd3324c82f3842994cc0ee3
[...]
```

then run `make makesum` and `make makeplist` (put the result in `pkg-plist` and remove the placeholder), run `make clean` and `make install`.

But make sure you still have the old multimedia/ffmpeg port in version 4 as version 6 is not compatible.

**Comment by huo-ju** [comment]
done https://github.com/huo-ju/photoprism-freebsd-port/commit/cd422f1c81df7e2062bc3656d110ce8dbdba45ff
