### ISSUE TITLE
photoprism cli "invalid assets path, check configuration and permissions"

### ISSUE THREAD

**Issue by semiligneous** [huo-ju/photoprism-freebsd-port#58]
firstly, @huo-ju Thanks for this project!

This is more of a question to help point me in right direction I think.

I am set up and it's all working, and now I want to automatically index new images I add (via a different process) daily/hourly. I can do this via the web UI (Library > Index > Start (scan)) manually.

Documentation suggests that it should be possible to use the cli and run `photoprism index`, and from there I was going to add this to cron.

However I get this error:

`invalid assets path, check configuration and permissions`

I am running as root, and get the same if I run it this way:

`su -m photoprism -c "photoprism index"`

In fact I get the same error when I run other cli command such as `photoprism stop`.

I can run `photoprism status` and result is `operational`.

`photoprism config` shows that there is indeed no value for the asset-path attribute, which is presumably what is causing the error.

I can stop and start the photoprism service using:

`service photoprism start|stop`

which works fine.

Is there a trick I am missing regarding using the cli tools under freebsd, all the official documentation seems to focus around docker builds.

Thanks in advance if you can offer any insight to get this going (scheduled re-indexing can't be such an unusual feature?!)

**Comment by steffenfritz** [comment]
Hi,

cron executes the command not in the correct context, I guess. Try to pass the --config-path and --assets-path flags in your job definition.

BTW: when you executed as root I could be that some rights are messed up.

**Comment by tinsukE** [comment]
Indeed, as stated on the [README](https://github.com/huo-ju/photoprism-freebsd-port#set-an-initial-admin-password-fresh-install) , the correct way to invoke the cli is to specify all the paths:

`photoprism --assets-path=/var/db/photoprism/assets --storage-path=/var/db/photoprism/storage --originals-path=/var/db/photoprism/storage/originals --import-path=/var/db/photoprism/storage/Import YOUR_COMMAND`

I recommend creating an alias!

**Comment by tinsukE** [comment]
Oh, another shortcut would be to set environment variables for the paths: https://docs.photoprism.org/getting-started/config-options/

**Comment by semiligneous** [comment]
What happens if the parameters passed conflict with the currently running instance? I assume that will cause problems! 

How does one confirm the actively running/correct paths for those options?



----- Original message -----

**Comment by tinsukE** [comment]
> What happens if the parameters passed conflict with the currently running instance?

If you have completely different paths, it'll probably be like running two instances of Photoprism on the same machine. If some are equal and others different, then you'll probably have a bad time.

> How does one confirm the actively running/correct paths for those options?

`ps auxww` did it for me:
```
/usr/local/bin/photoprism --defaults-yaml= --assets-path=/var/db/photoprism/assets --storage-path=/var/db/photoprism/storage --originals-path=/var/db/photoprism/storage/originals --import-path=/var/db/photoprism/storage/import start
```

**Comment by semiligneous** [comment]
can close this ticket
