### ISSUE TITLE
built failed with poudriere

### ISSUE THREAD

**Issue by svenjott** [huo-ju/photoprism-freebsd-port#6]
Tried to create a pkg with poudriere to use it in a dedicated jail (and most dependencies are available within poudriere as well). 

However it fails, see log excerpt 

```bash
===>   Returning to build of photoprism-g20210111
===========================================================================
=======================<phase: lib-depends    >============================
===========================================================================
=======================<phase: configure      >============================
===>  Configuring for photoprism-g20210111
===========================================================================
=======================<phase: build          >============================
===>  Building for photoprism-g20210111
cd /wrkdirs/usr/ports/www/photoprism/work/photoprism-6b0d94ff42fadccfe88c4d68744b9d3afea36e2f/docker/tensorflow && gmake download
gmake[1]: Entering directory '/wrkdirs/usr/ports/www/photoprism/work/photoprism-6b0d94ff42fadccfe88c4d68744b9d3afea36e2f/docker/tensorflow'
wget https://github.com/tensorflow/tensorflow/archive/v1.15.2.tar.gz
gmake[1]: wget: No such file or directory
gmake[1]: *** [Makefile:10: download] Error 127
gmake[1]: Leaving directory '/wrkdirs/usr/ports/www/photoprism/work/photoprism-6b0d94ff42fadccfe88c4d68744b9d3afea36e2f/docker/tensorflow'
*** Error code 2

Stop.
make: stopped in /usr/ports/www/photoprism
=>> Cleaning up wrkdir
===>  Cleaning for photoprism-g20210111
build of www/photoprism | photoprism-g20210111 ended at Wed Jan 27 10:17:10 CET 2021
build time: 00:00:30
!!! build failure encountered !!!
```

What should I try to solve this?

 Full [log.txt](https://github.com/huo-ju/photoprism-freebsd-port/files/5879386/log.txt) enclosed as well.

**Comment by abelbabel** [comment]
`wget` is missing.
Try to add  ftp/wget in Makefile as BUILD_DEPENDS

**Comment by svenjott** [comment]
Added wget:ftp/wget as BUILD_DEPENDS, however now it fails resolving https://github.com:

```bash
===>  Building for photoprism-g20210111
cd /wrkdirs/usr/ports/www/photoprism/work/photoprism-6b0d94ff42fadccfe88c4d68744b9d3afea36e2f/docker/tensorflow
gmake[1]: Entering directory '/wrkdirs/usr/ports/www/photoprism/work/photoprism-6b0d94ff42fadccfe88c4d68744b9d3
wget https://github.com/tensorflow/tensorflow/archive/v1.15.2.tar.gz
--2021-01-28 07:00:34--  https://github.com/tensorflow/tensorflow/archive/v1.15.2.tar.gz
Resolving github.com (github.com)... failed: Name does not resolve.
wget: unable to resolve host address 'github.com'
gmake[1]: *** [Makefile:10: download] Error 4
gmake[1]: Leaving directory '/wrkdirs/usr/ports/www/photoprism/work/photoprism-6b0d94ff42fadccfe88c4d68744b9d3a
*** Error code 2

Stop.
make: stopped in /usr/ports/www/photoprism
=>> Cleaning up wrkdir
===>  Cleaning for photoprism-g20210111
build of www/photoprism | photoprism-g20210111 ended at Thu Jan 28 08:00:44 CET 2021
build time: 00:00:36
!!! build failure encountered !!!
```

Which is strange since the builder jails are referring to the host' /etc/resolv.conf (and a ping to github.com resolves correctly).

**Comment by abelbabel** [comment]
This is strange indeed. I hadn't have this particular issue yesterday with a fresh installed, up-to-date 11.4-RELEASE (non-poudriere) jail and manual port `make`.

I think it was possible to interrupt/pause poudriere builds at a certain moment. Maybe you can try it and investigate within this jail if resolving at this moment is possible or not.

**Comment by abelbabel** [comment]
Have you seen [this](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250646#c2)? It states: "downloads aren't allowed during buiuld." Maybe related.

**Comment by svenjott** [comment]
> Have you seen [this](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250646#c2)? It states: "downloads aren't allowed during buiuld." Maybe related.

Well, it says everything... I tried a clean jail, installed the dependencies via pkg from the host and run make && make install. Well at least it downloaded tensorflow and started actual building but failed with another error message (related to tensorflow, not the the port itself). I guess with the information in your link the issue can be closed (and maybe a remark on can be given, that poudriere will not work at the moment due to tensorflow ;) )

Thanks for your help!

**Comment by psa** [comment]
@svenjott  (and for anyone tripping over this in the future): Poudriere has a configuration option which will allow it to download during the build: `ALLOW_NETWORKING_PACKAGES="photoprism"`

The README.md also has commentary about other things needed for Poudriere builds.
