### ISSUE TITLE
Photoprism not starting using new FreeBSD 13.1 build

### ISSUE THREAD

**Issue by tschettervictor** [huo-ju/photoprism-freebsd-port#64]
Photoprism installs fine using libtensorflow1 from [here](https://github.com/psa/libtensorflow1-freebsd-port/releases) and the build from [here](https://github.com/Gaojianli/photoprism-freebsd-port/releases) but it does not start.

`service photoprism start` shows `Starting photoprism.` but it does not start or show any obvious errors.

Any ideas?

**Comment by huo-ju** [comment]
It's hard to say without error logs. but the service scripts should be put to ```/usr/local/etc/rc.d/photoprism``` might you can find it and try to run it directly or open it and try to run the ```phptoprism``` bin without ```/usr/sbin/daemon``` , the at least you will have some error logs.

**Comment by tschettervictor** [comment]
I'm getting "Illegal Instruction" when trying that.

According to the docs, this might be because it was compiled with newer hardware?

**Comment by tschettervictor** [comment]
Even just trying `photoprism` without specifying any option returns `Illegal Instruction`

**Comment by huo-ju** [comment]
Illegal Instruction means the pre build binary compiled with some cpu
feature that your cpu not support. You can try to build it by yourself and
disable some feature flags.

**Comment by tschettervictor** [comment]
Will give it a try. How do I get the pkg build from the make install command?

**Comment by tschettervictor** [comment]
Build fails anyway on FreeBSD 13.2
I’ll stick with the 12 build for now

**Comment by tschettervictor** [comment]
Trying to build.

Build goes all the way to the end, but then errors out with pkg-static:file not found
Here Is the end output.

`pkg-static: Unable to access file /root/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nsfw/saved_model.pb:No such file or directory
pkg-static: Unable to access file /root/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nsfw/variables/variables.data-00000-of-00001:No such file or directory
pkg-static: Unable to access file /root/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nsfw/variables/variables.index:No such file or directory
pkg-static: Unable to access file /root/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nsfw/version.txt:No such file or directory
pkg-static: Unable to access file /root/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/facenet/:No such file or directory
pkg-static: Unable to access file /root/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nasnet/variables/:No such file or directory
pkg-static: Unable to access file /root/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nasnet/:No such file or directory
pkg-static: Unable to access file /root/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nsfw/variables/:No such file or directory
pkg-static: Unable to access file /root/photoprism-freebsd-port/work/stage/var/db/photoprism/assets/nsfw/:No such file or directory
pkg-static: duplicate file listing: /usr/local/etc/rc.d/photoprism, ignoring
*** Error code 1

Stop.
make: stopped in /root/photoprism-freebsd-port`

**Comment by huo-ju** [comment]
It looks the nsfw package not be downloaded, the code is https://github.com/huo-ju/photoprism-freebsd-port/blob/fc5adb75cdcf05b3c644e284eb0d9e02152706d4/Makefile#L52 and https://github.com/photoprism/photoprism/blob/develop/scripts/download-nsfw.sh

maybe you can remove all nsfw related files from https://github.com/huo-ju/photoprism-freebsd-port/blob/fc5adb75cdcf05b3c644e284eb0d9e02152706d4/pkg-plist#L146 and try to build it again.

**Comment by tschettervictor** [comment]
Build completed but with same Illegal Instruction as before.

Using all the defaults with `make config-recursive`

might just have to update the cpu

**Comment by Gaojianli** [comment]
avx2 is required with my build, I will change the readme.

**Comment by jbaptiste72** [comment]
Hi, i start with truenas core 13 and i have the same issue trying to install Photoprism on a jail  : "this program can only be run on amd64 processors with v3 microarchitecture support"
my cpu support avx but not avx2.

Gaojianli, is there something to do to delete avx2 requirement with your build ?

**Comment by Gaojianli** [comment]
> Hi, i start with truenas core 13 and i have the same issue trying to install Photoprism on a jail : "this program can only be run on amd64 processors with v3 microarchitecture support" my cpu support avx but not avx2.
> 
> Gaojianli, is there something to do to delete avx2 requirement with your build ?

you can try to build it with yourself,  run `make config` and choose the type of your CPU in the dialog

**Comment by jbaptiste72** [comment]
ok thanks :)

**Comment by lapo-luchini** [comment]
Or you can try [my build](https://github.com/lapo-luchini/photoprism-freebsd-port/releases/tag/2023-11-28), which only uses AVX and SSE42 (no AVX2).

**Comment by tschettervictor** [comment]
> Or you can try [my build](https://github.com/lapo-luchini/photoprism-freebsd-port/releases/tag/2023-11-28), which only uses AVX and SSE42 (no AVX2).

Just tried. Same issue. Illegal instruction when running the photoprism binary.
