### ISSUE TITLE
Update port to Photoprism 240711-2197af848

### ISSUE THREAD

**Issue by dml33** [huo-ju/photoprism-freebsd-port#72]
Hi,

Is it possible to update the port to the newest Photoprism release https://github.com/photoprism/photoprism/releases/tag/240711-2197af848

Maybe, issue #70 is fixed as well, if the `-r` parameter for the `cp` is changed to `-R` or it is done in other way it works in FreeBSD.

Thanks!!

**Comment by dml33** [comment]
@tinsukE Could you build `g20240420` correctly? I opened the issue #70 since, during the process, it copies files and the `-r` parameter is not supported in FreeBSD, but in Linux.

**Comment by tinsukE** [comment]
@dml33 I have investigated the build failure and wrote my findings on [that issue](https://github.com/huo-ju/photoprism-freebsd-port/issues/70).
