### ISSUE TITLE
missing libtensorflow1 et al makes building impossible

### ISSUE THREAD

**Issue by nkfilis** [huo-ju/photoprism-freebsd-port#74]
The [science/libtensorflow1](https://www.freshports.org/science/libtensorflow1/) port was removed from the ports tree, so was [devel/bazel029](https://www.freshports.org/devel/bazel029), which makes building libtensorflow1 pretty hard nowadays, at least using https://github.com/psa/libtensorflow1-freebsd-port it isn't straightforward anymore.

**Comment by huo-ju** [comment]
@lapo-luchini has a upgraded port, but the easiest way is that just use his binary. (install a non-official binary is not a best practices for sure.. but..)   [libtensorflow1-freebsd-port]( https://github.com/lapo-luchini/libtensorflow1-freebsd-port )

I think the ultimate solution is just move to pytorch, sooner or later.
