### ISSUE TITLE
Malformed conditional at "make config"

### ISSUE THREAD

**Issue by nikotschierske** [huo-ju/photoprism-freebsd-port#9]
When trying to install in a TrueNas Jail(Version 12.1-Release-p13 as well as Version 12.2-Release-p2) I get the error 
`make: "/usr/share/mk/bsd.port.mk" line 32: Cannot open /usr/ports/Mk/bsd.port.mk
make: "/photoprism-freebsd-port/Makefile" line 44: Malformed conditional (${OPSYS} == FreeBSD && ${OSVERSION} > 1100000 && ${OSVERSION} < 1200000)`

after the 'make config' command.

**Comment by huo-ju** [comment]
The ```make``` can't find your ```bsd.port.mk```, and I think you need full ports tree for build it.

**Comment by nikotschierske** [comment]
I fixed my bsd.port.mk and still get the error: 
`make: "/photoprism-freebsd-port/Makefile" line 44: Malformed conditional (${OPSYS} == FreeBSD && ${OSVERSION} > 1100000 && ${OSVERSION} < 1200000)
make: Fatal errors encountered -- cannot continue
make: stopped in /photoprism-freebsd-port`

**Comment by huo-ju** [comment]
Can you provide me the output of ```make -V OPSYS``` and ```make -V OSVERSION```? Run the command under ```/photoprism-freebsd-port``` dir. Thanks.
